### ISSUE TITLE
Slow CrossProduct algorithm between two Vector3

### ISSUE THREAD

**Issue by captain-yoshi** [BurksEngineering/TcTransform#4]
This issue is somewhat related to #2.

I have a control loop of 1 kHz. In each loop, my program does 42 CrossProduct with `Vector3` objects. With the default methods, my program has a latency of `1100 usec`. When doing my own function for 3D vectors the latency drops down to `470 usec`.

I propose the creation of the `Vector3_CrossProduct` function to improve on the speed of the more generic cross product function.

```cpp
FUNCTION Vector3_CrossProduct : BOOL
VAR_IN_OUT CONSTANT
    A : Vector3;
    B : Vector3;
END_VAR
VAR_IN_OUT
    Res : Vector3;
END_VAR
---

// Validate variable input output variables ?

// Complexity : 6M+3A
Res.SetI(0, A.GetI(1)*B.GetI(2) - A.GetI(2)*B.GetI(1));
Res.SetI(1, A.GetI(2)*B.GetI(0) - A.GetI(0)*B.GetI(2));
Res.SetI(2, A.GetI(0)*B.GetI(1) - A.GetI(1)*B.GetI(0));

Vector3_CrossProduct := TRUE;
```

**Comment by BurksEngineering** [comment]
Great idea. I added a Fector3_CrossProduct function to TcTransform then modified Vector3.GetVector3CrossProduct() and Vector3.SetAsVector3CrossProduct() to use this algorithm instead of the generic one.
